### ISSUE TITLE
Incorrect assertion for multi-line sequence points

### ISSUE THREAD

**Issue by pkrukp** [AaronRobinsonMSFT/PPDB#4]
Hello,

### Problem description

Streams.cpp line 366 has following assertion: 
```
        pt.EndColumn = pt.StartColumn + colRange;
        assert(pt.EndColumn < 0x10000);
        assert(pt.StartLine == pt.EndLine || pt.StartColumn < pt.EndColumn); // line 366
```

The condition evaluates to false for following code:
```
        static string GetPipeName() => IsWindows
        ? "a"
        : "b";
```
Here, the sequence points represents conditional operator, so start line is < end line, but start column is > end column. For example (9,40) - (11,14).

### Fix 

I assume the intention was to check if StartColumn < EndColumn only if they are in the same line:
```
        assert(pt.StartLine == pt.EndLine ? pt.StartColumn < pt.EndColumn : true);
```

By the way, can `StartColumn == EndColumn`  (for one-line sequence points)?

**Comment by AaronRobinsonMSFT** [comment]
Fixed with ca90cdd3914ed8d4a4e7cd1419a4f134cfd8525b

>By the way, can StartColumn == EndColumn (for one-line sequence points)?

@pkruk2 I don't believe so. That would require a statement being a single character and I can't think of one off the top of my head. If you can construct one please let me know.

**Comment by pkrukp** [comment]
> Fixed with ca90cdd

Thanks.

This is just a nitpicking, but the "pt.StartLine < pt.EndLine" check seems redundant, as it was verified three lines above:
```
        // Compute ends
        pt.EndLine = pt.StartLine + lineRange;
        assert(pt.EndLine < 0x20000000 && pt.EndLine != 0xfeefee);
        assert(pt.StartLine <= pt.EndLine);

        pt.EndColumn = pt.StartColumn + colRange;
        assert(pt.EndColumn < 0x10000);
        assert(pt.StartLine == pt.EndLine ? pt.StartColumn < pt.EndColumn : pt.StartLine < pt.EndLine);
```

> That would require a statement being a single character and I can't think of one off the top of my head. If you can construct one please let me know.

I agree. In fact it would have to be a zero-lenght character it seems - in `static int GetOne() => 1 ;` the "1" has a sequence point but EndColumn == StartColumn+1

**Comment by AaronRobinsonMSFT** [comment]
@pkruk2 Agreed on it being redundant. I don’t like ‘true’ in my asserts normally. If you find it more precise I can change it though.

**Comment by pkrukp** [comment]
I think it's not worth spending your time on it :)
